### ISSUE TITLE
Prevent CrowedMod from working on normal Among Us servers (maybe?)

### ISSUE THREAD

**Issue by MatadorProBr** [CrowdedMods/CrowdedMod#30]
I was doing a little research on CrowdedMod in YouTube until I found this video: 
[![Video](https://user-images.githubusercontent.com/71022656/118262158-db242e00-b48a-11eb-8ff0-881839b5b2a0.png)](https://www.youtube.com/watch?v=aa4F6B6tX8U)
which I think is funny and that he is gaining a lot of view for doing something that is practically considered a hack instead of him doing it on private servers like Impostor, hopefully see my issue and solve it.

**Comment by Galster-dev** [comment]
This is actually fun a bit because previously you were not able to create lobbies with player limit > 10 (kicked for invalid game data) 

IS preparing for 15-players lobby??

**Comment by Pietrodjaowjao** [comment]
i maked this

**Comment by Galster-dev** [comment]
Hello! The issue has been solved by InnerSloth. Thank you for your patience!
