### ISSUE TITLE
Vitals is broken

### ISSUE THREAD

**Issue by MapleEve** [CrowdedMods/CrowdedMod#33]
![image](https://user-images.githubusercontent.com/1845053/169576785-2f3f75b2-adaa-4df0-83a9-744e650dcb45.png)

Reactor 1.2.5
rc 2.7.0
TOR 4.1.3

**Comment by Galster-dev** [comment]
Hello!

Kinda silly mistake, messed up Y and X as you can probably see 🟢🐖 

Could you try with this one? https://github.com/CrowdedMods/CrowdedMod/suites/6595543288/artifacts/247559940

**Comment by MapleEve** [comment]
> Hello!
> 
> Kinda silly mistake, messed up Y and X as you can probably see 🟢🐖
> 
> Could you try with this one? https://github.com/CrowdedMods/CrowdedMod/suites/6595543288/artifacts/247559940

It's okay now.
