### ISSUE TITLE
[Feature] Add Submerged Map support.

### ISSUE THREAD

**Issue by MapleEve** [CrowdedMods/CrowdedMod#35]
As the largest map, Submerged is become more and more famous nowadays.
So if it's possible to support Submerged?

**Comment by Galster-dev** [comment]
Hello!

I've answered in discord already, but giving a quick look to their mod guidelines CM should support submerged already. Did you find any incompatibilities? If so - please report here

**Comment by MapleEve** [comment]
> Hello!
> 
> I've answered in discord already, but giving a quick look to their mod guidelines CM should support submerged already. Did you find any incompatibilities? If so - please report here

The submerged is using BE.559 and the 2.7.0 is using BE.562 it's huge difference.

**Comment by MapleEve** [comment]
Bug 1:

When Host a game, the Imposter  9  and  10 button is override with Submerged Map choose.

**Comment by Galster-dev** [comment]
Impostor pick on create game options should be kinda reworked. But still you can change impostor amount later in game settings

**Comment by Galster-dev** [comment]
Hello. Finally got time to do it. Could you test with [this build](https://github.com/CrowdedMods/CrowdedMod/actions/runs/2658337977) ?

**Comment by Tommy-XL** [comment]
I decided to check the assembly, the error reported by the author was fixed
