### ISSUE TITLE
The ability to change the number of "Assassin in the mod Town Of Us

### ISSUE THREAD

**Issue by Tommy-XL** [CrowdedMods/CrowdedMod#37]
Is it possible to add the ability in CrowdedMod to put the number of "Assassins" more than 3 in the Town Of Us mod?
(This role in the game can guess the roles but when there are 5 traitors in the game, only 3 of them can guess the roles)
![unknown](https://user-images.githubusercontent.com/104814436/173039414-005b1048-d926-4f4a-a727-4689a3b927a7.png)

Or do you have to contact the developers of Town Of Us with this problem?

**Comment by Galster-dev** [comment]
Hello! This mod is not meant to unlock player-related counts on every mod - it's just simply too hard to support

But you can ask ToU devs to support this mod on their side. If you or mod devs need additional support, they can join our [Discord](https://discord.gg/XEc7PdDTyn)
