### ISSUE TITLE
Bug during meetings

### ISSUE THREAD

**Issue by Tommy-XL** [CrowdedMods/CrowdedMod#38]
Found a bug in the game that when a player dies during a vote, his position immediately changes to the very end (it must be so that the position does not change until the next meeting takes place)

Positions of players before kill:
![1111](https://user-images.githubusercontent.com/104814436/173799859-be4a1aa9-aad3-407b-b025-58703bf9e277.png)

Kill animation
![2222](https://user-images.githubusercontent.com/104814436/173799908-2c24f41a-aafb-4cf1-9e76-98640bc7ab5c.png)

Positions of the players after the kill
![3333](https://user-images.githubusercontent.com/104814436/173799938-87a4ab7a-7851-475a-9f3f-aefd6a2afdc3.png)

**Comment by Galster-dev** [comment]
Hello!

This is intended because the mod is focused on high player count

**Comment by Tommy-XL** [comment]
Can make an additional option in the settings to enable or disable this feature?

**Comment by Galster-dev** [comment]
Why is it so important?

**Comment by Tommy-XL** [comment]
It's not that it's important, but for the "Town Of Us" and "The Other Roles" mod, a more important function, because when guessing the player, he abruptly changes position and goes to the very end and the orientation is lost who was alive and guessed, and who was already dead

**Comment by Tommy-XL** [comment]
In fact, you can leave this function
