### ISSUE TITLE
Change the way the vote-kick menu works

### ISSUE THREAD

**Issue by RobinRMC** [CrowdedMods/CrowdedMod#39]
When playing with a lot of players, people can easily be targeted by players and get vote-kicked. Maybe it's an idea to change the vote-kick menu so that only the host can use it to kick/ban people out of their lobby.

**Comment by Galster-dev** [comment]
Hello!

This decision is controversial so, if implemented, it needs in-game switch (like an option) which is a lot for a small mod that tries to not conflict with anything else. I'd like to see more possible solutions.

@przebor

**Comment by RobinRMC** [comment]
Maybe an additional mod that you can install for this feature? (Like an add-on of some sort.)

**Comment by Galster-dev** [comment]
Hello. The subproject has been created

https://github.com/CrowdedMods/CrowdedMod.HostOnlyKick

**Comment by RobinRMC** [comment]
> Hello. The subproject has been created
> 
> https://github.com/CrowdedMods/CrowdedMod.HostOnlyKick

Awesome! Thank you so much!
