### ISSUE TITLE
Players falling off the screen

### ISSUE THREAD

**Issue by RobinRMC** [CrowdedMods/CrowdedMod#40]
In meetings, players are falling off the screen instead of being put on other pages. (Same goes for the shapeshifter menu.)

**Comment by RobinRMC** [comment]
> In meetings, players are falling off the screen instead of being put on other pages. (Same goes for the shapeshifter menu.)

I am using the latest artifact btw.

**Comment by Galster-dev** [comment]
Do you use any other mods?

**Comment by RobinRMC** [comment]
> Do you use any other mods?

Yes.
- BetterPolus
- ColorsPlus
- Reactor (of course)
- Submerged

**Comment by Galster-dev** [comment]
Giving a quick look I don't see any incompatibilities. Could you try disabling them one by one? You can use [Reactor.Debugger](https://github.com/NuclearPowered/Reactor/actions/runs/2436775097) plugin to spawn dummies to overflow first page

**Comment by RobinRMC** [comment]
Testing is a bit hard, because I do it alone right now. Last time I tested, I had to open 19 instances of Among Us. :/

**Comment by Galster-dev** [comment]
As I just said you can use freeplay and Reactor.Debugger mod to spawn enough dummies

**Comment by RobinRMC** [comment]
Oh, I didn't know that. I'm not sure if I can test everything today though.

**Comment by RobinRMC** [comment]
It still happens with just CrowdedMod and Reactor installed.

**Comment by Galster-dev** [comment]
Could you try with https://github.com/CrowdedMods/CrowdedMod/actions/runs/2521993373 ?

**Comment by Tommy-XL** [comment]
In this patch, the ability to turn the page on the vote is gone

**Comment by Galster-dev** [comment]
https://github.com/CrowdedMods/CrowdedMod/actions/runs/2523720996

**Comment by Galster-dev** [comment]
Well I've been doing this through Github editor but it needs more research
Will fix soon

**Comment by Galster-dev** [comment]
Hello!

https://github.com/CrowdedMods/CrowdedMod/actions/runs/2529236406

**Comment by Tommy-XL** [comment]
Voting has been fixed in this patch, but the shapeshifter menu remains dropdown
![2121](https://user-images.githubusercontent.com/104814436/174618591-ca1a56f2-0cb9-4125-859c-fae763bc1998.png)

**Comment by Galster-dev** [comment]
Closing as completed and merging #41

Please make a new issue for shapeshifter UI
