### ISSUE TITLE
bug in the voting window

### ISSUE THREAD

**Issue by Tommy-XL** [CrowdedMods/CrowdedMod#44]
When it shows all players, some inscriptions pop up

Video demonstration of the bug:
https://drive.google.com/file/d/1YgeF_gRA6ODY0p3bDaqlVXZfADmEsuyE/view?usp=sharing

**Comment by Tommy-XL** [comment]
I forgot to say that this is version 2.7.0

**Comment by RobinRMC** [comment]
There's also a glitch when the timer ends.

**Comment by Tommy-XL** [comment]
Hm, I checked everything seems to be ok

**Comment by Galster-dev** [comment]
Hello! [this build](https://github.com/CrowdedMods/CrowdedMod/actions/runs/2652803289) should fix the issue

**Comment by Galster-dev** [comment]
> There's also a glitch when the timer ends.

@RobinRMC This issue should be fixed in [this commit](https://github.com/CrowdedMods/CrowdedMod/actions/runs/2652839262). If it's still there, please create a new issue

**Comment by Tommy-XL** [comment]
I checked both builds, and both builds fixed the problem with a blank page and the appearance of incomprehensible inscriptions on the vote. Waiting for feedback from @RobinRMC

**Comment by RobinRMC** [comment]
I can't reproduce the issue at the moment, because I need to test it with other people. (The bug I was talking about is not visible in freeplay.)
